version: '3.7'

services:
  db:
    container_name: django-docker-db
    image : mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’

  # web:
  #   container_name: management
  #   # command: python3 manage.py runserver 0.0.0.0:8000
  #   image: 038183792649.dkr.ecr.ap-northeast-1.amazonaws.com/myselfmanagement
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - web:/var/run/web
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - SELF_MANAGEMENT_SECRET_KEY
  #   depends_on:
  #     - db

  web:
    restart: always
    build: ./selfmanagement
    expose:
      - "8000"
    depends_on:
      - db
    command: bash -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    environment:
      - SELF_MANAGEMENT_SECRET_KEY
    volumes:
      - ./selfmanagement:/usr/src/app
      - ./selfmanagement/static/:/usr/src/app/static

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

volumes:
  gunicorn:
    driver: local
  db: {}
