version: '3'

services:
  web:
    container_name: management
    build: . 
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SELF_MANAGEMENT_SECRET_KEY

  db:
    container_name: django-docker-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’

