version: '3.7'

services:
  db:
    container_name: sm-db
    build: ./mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: selfmanagement
      MYSQL_PASSWORD: self1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    expose:
      - "3306"

  web:
    container_name: sm-app
    restart: always
    build: ./self_management
    expose:
      - "8000"
    depends_on:
      - db
    command: bash -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
      
  ng:
    container_name: sm-ng
    build: ./nginx
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"   
    volumes:
      - "./nginx/:/etc/nginx/"
    environment:
      - ROOT=/var/www/
    links:
      - web:web

volumes:
  db: {}