version: '3.7'

services:
  db:
    container_name: sm-db
    build: ./mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: selfmanagement
      MYSQL_PASSWORD: self1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    expose:
      - "3306"

  web:
    container_name: sm-app
    restart: always
    build: ./self_management
    expose:
      - "8000"
    volumes:
      - ./static:/static
    depends_on:
      - db
    command: bash -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    # command: bash -c "python manage.py runserver"
      
  ng:
    container_name: sm-ng
    restart: always
    image: nginx:1.17.7
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./static:/static
    links:
      - web:web

volumes:
  db: {}