version: '3.7'

services:
  db:
    container_name: django-docker-db
    image : mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’

  # web:
  #   container_name: management
  #   # command: python3 manage.py runserver 0.0.0.0:8000
  #   image: 038183792649.dkr.ecr.ap-northeast-1.amazonaws.com/myselfmanagement
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - web:/var/run/web
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - SELF_MANAGEMENT_SECRET_KEY
  #   depends_on:
  #     - db

  gunicorn:
    image: gunicorn:latest
    container_name: gunicorn
    environment:
      - SELF_MANAGEMENT_SECRET_KEY
    volumes:
      - .:/usr/src/app
      - gunicorn:/var/run/gunicorn
    depends_on:
      - db

  nginx:
    image: nginx:1.17.7
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
    depends_on: 
      - gunicorn
volumes:
  gunicorn:
    driver: local
  db: {}
