version: '3.7'

services:
  db:
    container_name: sm-db
    # hostname: "127.0.0.1"
    build: ./mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: selfmanagement
      MYSQL_PASSWORD: self1234
      # MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - "3306"

  web:
    container_name: sm-app
    restart: always
    build: ./self_management
    expose:
      - "8000"
    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py collectstatic && gunicorn config.wsgi -b 0.0.0.0:8000"
    environment:
      - SELF_MANAGEMENT_SECRET_KEY
    volumes:
      - ./self_management:/usr/src/app
      # - ./self_management/static:/usr/src/static

  ng:
    container_name: sm-ng
    build: ./nginx
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
    volumes_from:
      - web
    links:
      - web:web

volumes:
  db: {}