version: '3'

services:
  django:
    container_name: management
    build: . 
    command: python3 manage.py runserver 0.0.0.0:80
    image: 038183792649.dkr.ecr.ap-northeast-1.amazonaws.com/myselfmanagement:latest
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - SELF_MANAGEMENT_SECRET_KEY
    depends_on:
      - mysql

  mysql:
    container_name: django-docker-db
    image : mysql:8.0.19
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
volumes:
  db-data:
