# Generated by Django 3.1.3 on 2020-11-26 21:42

from django.db import migrations, models
import weekly_action.models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0004_auto_20201127_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyaction',
            name='score',
            field=models.IntegerField(blank=True, help_text='アクションを終えたら入力', null=True, validators=[weekly_action.models.clean_score], verbose_name='自己評価'),
        ),
    ]
