# Generated by Django 3.1.3 on 2020-11-26 22:08

from django.db import migrations, models
import weekly_action.models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0005_auto_20201127_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyaction',
            name='goal_action',
            field=models.CharField(help_text='１週間で実践する行動', max_length=255, verbose_name='目標達成の為のアクション'),
        ),
        migrations.AlterField(
            model_name='weeklyaction',
            name='score',
            field=models.IntegerField(blank=True, help_text='アクションを終えたら入力（範囲１〜５）', null=True, validators=[weekly_action.models.clean_score], verbose_name='自己評価'),
        ),
    ]
