# Generated by Django 3.1.3 on 2020-11-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0006_auto_20201127_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyaction',
            old_name='why_need_goal',
            new_name='why_select_action',
        ),
    ]
