# Generated by Django 3.1.3 on 2020-11-27 22:18

from django.db import migrations, models
import weekly_action.models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0009_auto_20201128_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyaction',
            name='score',
            field=models.IntegerField(blank=True, help_text='アクションを終えたら入力（範囲１〜５）', null=True, validators=[weekly_action.models.clean_score], verbose_name='自己評価'),
        ),
    ]
