# Generated by Django 3.1.2 on 2020-11-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='custom_user',
            new_name='custom_user_id',
        ),
    ]
