# Generated by Django 3.1.2 on 2020-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0003_auto_20201115_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='year'),
        ),
    ]
