# Generated by Django 3.1.2 on 2020-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0004_auto_20201116_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='month',
            field=models.IntegerField(default=11, verbose_name='month'),
        ),
    ]
