# Generated by Django 3.1.2 on 2020-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0005_auto_20201116_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='category',
            field=models.CharField(blank=True, choices=[('', '選択肢から選んでください'), ('0', '健康'), ('1', 'ビジネス'), ('2', '学習'), ('3', '家事'), ('4', 'プライベート'), ('5', 'アウトドア・旅行'), ('6', 'その他')], max_length=255, null=True, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='goal',
            field=models.CharField(help_text='1〜数ヶ月で達成したい目標', max_length=255, verbose_name='達成目標'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='month',
            field=models.IntegerField(default=11, verbose_name='目標期限（月末）'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='revised_goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='修正目標'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='sccore',
            field=models.IntegerField(blank=True, help_text='目標達成及び期限が来たら入力', null=True, verbose_name='自己評価'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='why_need_goal',
            field=models.TextField(blank=True, help_text='なぜその目標を達成したいのか？（未設定可）', max_length=255, null=True, verbose_name='目標設定動機'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='why_revise',
            field=models.TextField(blank=True, help_text='なぜ目標を修正するのか？（未設定可）', max_length=255, null=True, verbose_name='目標修正理由'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='目標期限（年）'),
        ),
    ]
