# Generated by Django 3.1.3 on 2020-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0007_auto_20201122_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='score',
            field=models.IntegerField(blank=True, choices=[('', '自己評価'), ('0', 1), ('1', 2), ('2', 3), ('3', 4), ('4', 5)], help_text='目標達成及び期限が来たら入力', null=True, verbose_name='自己評価'),
        ),
    ]
