# Generated by Django 3.1.3 on 2020-11-26 21:42

from django.db import migrations, models
import monthly_goal.models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0008_auto_20201127_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='score',
            field=models.IntegerField(blank=True, help_text='目標達成及び期限が来たら入力', null=True, validators=[monthly_goal.models.clean_score], verbose_name='自己評価'),
        ),
    ]
