# Generated by Django 3.1.3 on 2020-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0010_auto_20201127_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='afte_memo',
            field=models.TextField(blank=True, help_text='評価の際の反省点などの後から振り返るメモ（未設定可）', max_length=500, null=True, verbose_name='後書きメモ'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='why_need_goal',
            field=models.TextField(blank=True, help_text='なぜその目標を達成したいのか？（未設定可）', max_length=500, null=True, verbose_name='目標設定動機'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='why_revise',
            field=models.TextField(blank=True, help_text='なぜ目標を修正するのか？（未設定可）', max_length=500, null=True, verbose_name='目標修正理由'),
        ),
    ]
