version: '3.7'

services:
  db:
    container_name: django-docker-db
    build : ../mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’

  web:
    restart: always
    build: .
    image: 038183792649.dkr.ecr.ap-northeast-1.amazonaws.com/myselfmanagement
    expose:
      - "8000"
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    environment:
      - SELF_MANAGEMENT_SECRET_KEY
    volumes:
      - .:/usr/src/app
      - ./static/:/usr/src/app/static

  nginx:
    restart: always
    build: ../nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/:/etc/nginx/
      - ./static/:/usr/src/app/static

    volumes_from:
      - web
    links:
      - web:web

volumes:
  db: {}

