# Generated by Django 3.1.3 on 2020-11-26 22:08

from django.db import migrations, models
import monthly_goal.models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0009_auto_20201127_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='goal',
            field=models.CharField(help_text='その月で達成したい目標', max_length=255, verbose_name='達成目標'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='month',
            field=models.IntegerField(default=11, validators=[monthly_goal.models.clean_month], verbose_name='目標期限（月末）'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='score',
            field=models.IntegerField(blank=True, help_text='目標達成及び期限が来たら入力（範囲１〜５）', null=True, validators=[monthly_goal.models.clean_score], verbose_name='自己評価'),
        ),
    ]
