# Generated by Django 3.1.3 on 2020-11-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0011_auto_20201128_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='afte_memo',
            new_name='after_memo',
        ),
    ]
