# Generated by Django 3.1.3 on 2020-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0007_auto_20201128_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyaction',
            name='why_select_action',
            field=models.TextField(blank=True, help_text='なぜそのアクションで目標が達成できるのか？（未設定可）', max_length=500, null=True, verbose_name='アクション設定理由'),
        ),
    ]
