# Generated by Django 3.1.3 on 2020-11-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0008_auto_20201128_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyaction',
            name='score',
        ),
        migrations.AddField(
            model_name='weeklyaction',
            name='after_memo',
            field=models.TextField(blank=True, help_text='評価の際の反省点などの後から振り返るメモ（未設定可）', max_length=500, null=True, verbose_name='後書きメモ'),
        ),
    ]
