# Generated by Django 3.1.3 on 2020-11-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_action', '0003_auto_20201127_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyaction',
            name='score',
            field=models.IntegerField(blank=True, choices=[('', '自己評価'), ('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5')], help_text='アクションを終えたら入力', null=True, verbose_name='自己評価'),
        ),
    ]
