# Generated by Django 3.1.2 on 2020-11-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_goal', '0006_auto_20201122_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='score',
            new_name='score',
        ),
    ]
