# Generated by Django 3.1.3 on 2020-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='住所'),
        ),
    ]
